### ISSUE TITLE
Dynamic animation loop

### ISSUE THREAD

**Issue by ghost** [infamous/infamous#3]
I'm working on a system so that animation frames only happen on elements that are receiving updates (in the [dynamic-raf](https://github.com/infamous/infamous/tree/dynamic-raf) branch). The process of making this requires that certain logic be moved into DOMRenderer (no WebGLRenderer yet, but these steps will help plan for that).

- [x] wrap logic in Node.render with requestAnimationFrame
- [x] Move all add-child logic from Node.render to Node.addChild.
- [x] Move all remove-child logic from Node.render to Node.removeChild.
- [x] Make a central loop (currently in the Scene class, one per scene, but should be moved out of Scene so it can apply to any number of scenes.)
- [x] Nodes should request updates, which places the requested update into a queue so it can be executed from the central loop.

**Comment by trusktr** [comment]
Finished in 6178a51340ee132e554982df170b24ccac3939c9
