### ISSUE TITLE
motor-html: Make motor-scene and motor-node elements be the direct elements of Node instances.

### ISSUE THREAD

**Issue by ghost** [infamous/infamous#4]
For example, if we write this HTML:

```html
<motor-scene ...>
  <motor-node ...>
  </motor-node>
</motor-scene>
```

then instead the imperative API creating a whole separate DOM tree where each DOM element is associated with a Node in the scene graph, have the imperative API adopt the `<motor-scene>` and `<motor-node>` elements directly as the elements associated with each Node of the scene graph.

For example, the current result of the above HTML is something like this (some details skipped for brevity):

```html
<motor-scene ...>
  <motor-node ...>
  </motor-node>
  <div class="motor-scene" ...>
    <div class="motor-node" ...>
    </div>
  </div>
</motor-scene>
```

That new DOM (the `<div>` elements) is what is currently actually manipulated by the behind-the-scenes imperative API.

Instead, we want the DOM to remain the same, and for the imperative API (when used via the HTML API) to manage the user's actual elements, so the final result will just be

```html
<motor-scene ...>
  <motor-node ...>
  </motor-node>
</motor-scene>
```

like the first example, with CSS styling (matrix transforms, etc) applied directly to those custom elements.

**Comment by trusktr** [comment]
Cases to test:

- [ ] `<motor-node>` gets appended to parent `<motor-node>`
  - It should make corresponding imperative Node to become child of the parent motor-node's imperative Node.
- [ ] `<motor-node>` gets removed from parent `<motor-node>`
  - It should make corresponding child imperative Node be removed from the parent motor-node's imperative Node.
